//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class animal
    {
        public int cod { get; set; }
        public string name { get; set; }
        public string raca { get; set; }
        public Nullable<int> dono { get; set; }
    //terte
        public virtual Pessoa Pessoa { get; set; }
    }
}
