# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - MyAppParodieCont

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b93be6a34dd24dbb89dd347d62c22a8c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_58e181d4072447ea996b99d375c79cb8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b93be6a34dd24dbb89dd347d62c22a8c }}/mcr.microsoft.com/dotnet/aspnet:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'MyAppParodieCont'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b5260a11b4164254bac139b98d99c12a }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b93be6a34dd24dbb89dd347d62c22a8c }}/mcr.microsoft.com/dotnet/aspnet:${{ github.sha }}'