name: My Complete CI/CD Action

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/myappparodiecontapp-AutoDeployTrigger-a6a64822-d007-47ef-9de3-597d763f4853.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:

  build:
    
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restores Packages
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore

    - name: Publish to folder
      run: msbuild myapp/myapp.csproj /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
         name: ASP-app
         path: '/published/**'

  postbuild:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ASP-app

  builddocker:
    runs-on: ubuntu-latest
    needs: postbuild

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
           registry: myappcontregistry.azurecr.io
           username: ${{ secrets.MYAPPPARODIECONTAPP_REGISTRY_USERNAME }}
           password: ${{ secrets.MYAPPPARODIECONTAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
           push: true
           tags: myappcontregistry.azurecr.io/myappparodiecontapp:${{ github.sha }}
           file: ./Dockerfile
  deploy:
      runs-on: ubuntu-latest
      needs: builddocker

      steps:
         - name: Azure Login
           uses: azure/login@v1
           with:
              creds: ${{ secrets.MYAPPPARODIECONTAPP_AZURE_CREDENTIALS }}


         - name: Deploy to containerapp
           uses: azure/CLI@v1
           with:
              inlineScript: |
                 az config set extension.use_dynamic_install=yes_without_prompt
                 az containerapp registry set -n myappparodiecontapp -g groupcont --server myappcontregistry.azurecr.io --username  ${{ secrets.MYAPPPARODIECONTAPP_REGISTRY_USERNAME }} --password ${{ secrets.MYAPPPARODIECONTAPP_REGISTRY_PASSWORD }}
                 az containerapp update -n myappparodiecontapp -g groupcont --image myappcontregistry.azurecr.io/myappparodiecontapp:${{ github.sha }}
